#!/bin/bash
set -euo pipefail

# ═══════════════════════════════════════════════════════════════
# Generate config.yaml for dev environment
# Detects defaults from system, prompts for confirmation
# ═══════════════════════════════════════════════════════════════

DEVENV_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_FILE="$DEVENV_DIR/config.yaml"

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${BLUE}[CONFIG]${NC} $1"; }
ok()   { echo -e "${GREEN}[OK]${NC}     $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC}   $1"; }

prompt() {
  local var_name="$1"
  local description="$2"
  local default="$3"
  local value

  echo -en "  ${description} [${GREEN}${default}${NC}]: "
  read -r value
  value="${value:-$default}"
  eval "$var_name=\"$value\""
}

echo ""
echo "============================================"
echo "  Dev Environment — Configuration Setup"
echo "============================================"
echo ""

if [ -f "$CONFIG_FILE" ]; then
  warn "config.yaml already exists at $CONFIG_FILE"
  echo -n "  Overwrite? (y/N): "
  read -r overwrite
  if [[ "$overwrite" != "y" && "$overwrite" != "Y" ]]; then
    echo "  Keeping existing config.yaml"
    exit 0
  fi
fi

# ─── Detect defaults ──────────────────────────────────────────

DEFAULT_DEV_DIR="$HOME/development"
DEFAULT_NVM_DIR="${NVM_DIR:-$HOME/.nvm}/versions/node"
DEFAULT_RVM_DIR="${rvm_path:-$HOME/.rvm}"
DEFAULT_KAFKA_HOME=""
DEFAULT_ES_BIN=""

# Try to find Kafka
if [ -d "$DEFAULT_DEV_DIR/kafka" ]; then
  KAFKA_FOUND=$(find "$DEFAULT_DEV_DIR/kafka" -maxdepth 1 -name "kafka_*" -type d 2>/dev/null | head -1)
  if [ -n "$KAFKA_FOUND" ]; then
    DEFAULT_KAFKA_HOME="$KAFKA_FOUND"
  fi
fi

# Try to find Elasticsearch
ES_FOUND=$(find "$DEFAULT_DEV_DIR/elasticsearch" -name "elasticsearch" -path "*/bin/*" -type f 2>/dev/null | head -1)
if [ -n "$ES_FOUND" ]; then
  DEFAULT_ES_BIN="$ES_FOUND"
fi

# Detect Node versions
detect_node_version() {
  local major="$1"
  if [ -d "$DEFAULT_NVM_DIR" ]; then
    ls -d "$DEFAULT_NVM_DIR"/v${major}.* 2>/dev/null | sort -V | tail -1 | xargs basename 2>/dev/null || echo ""
  fi
}

DEFAULT_NODE16=$(detect_node_version 16)
DEFAULT_NODE18=$(detect_node_version 18)
DEFAULT_NODE20=$(detect_node_version 20)
DEFAULT_NODE22=$(detect_node_version 22)

# Detect Ruby
DEFAULT_RUBY_VERSION=""
DEFAULT_RUBY_GEMSET=""
if command -v rvm &>/dev/null; then
  DEFAULT_RUBY_VERSION=$(rvm list strings 2>/dev/null | grep "ruby-2" | tail -1 || echo "ruby-2.6.6")
  DEFAULT_RUBY_GEMSET=$(rvm gemset list 2>/dev/null | grep "rails" | head -1 | xargs || echo "rails602")
fi
DEFAULT_RUBY_VERSION="${DEFAULT_RUBY_VERSION:-ruby-2.6.6}"
DEFAULT_RUBY_GEMSET="${DEFAULT_RUBY_GEMSET:-rails602}"

# ─── Prompt for values ────────────────────────────────────────

log "Paths"
prompt DEV_DIR "Development directory" "$DEFAULT_DEV_DIR"
prompt KAFKA_HOME "Kafka home directory" "$DEFAULT_KAFKA_HOME"
prompt ES_BIN "Elasticsearch binary path" "$DEFAULT_ES_BIN"

echo ""
log "Node.js (nvm)"
prompt NVM_DIR "nvm versions directory" "$DEFAULT_NVM_DIR"
prompt NODE16 "Node 16 version (seleniumhub)" "${DEFAULT_NODE16:-v16.20.2}"
prompt NODE18 "Node 18 version (testhub)" "${DEFAULT_NODE18:-v18.12.1}"
prompt NODE20 "Node 20 version (pusher, fe)" "${DEFAULT_NODE20:-v20.17.0}"
prompt NODE22 "Node 22 version (frontend-o11y)" "${DEFAULT_NODE22:-v22.15.0}"

echo ""
log "Ruby (rvm)"
prompt RVM_DIR "rvm directory" "$DEFAULT_RVM_DIR"
prompt RUBY_VERSION "Ruby version" "$DEFAULT_RUBY_VERSION"
prompt RUBY_GEMSET "Rails gemset name" "$DEFAULT_RUBY_GEMSET"

echo ""
log "Database credentials"
prompt PG_USER "PostgreSQL user" "browserstack"
prompt PG_PASS "PostgreSQL password" "Password123"
prompt PG_DB "PostgreSQL database" "obs"
prompt MY_USER "MySQL user" "root"
prompt MY_PASS "MySQL password" "Root@123"
prompt MY_TESTHUB_DB "MySQL testhub database" "testhub_database"
prompt ES_USER "Elasticsearch user" "elastic"
prompt ES_PASS "Elasticsearch password" "random@123"

echo ""
log "Git"
prompt GIT_ORG "GitHub org for repos" "browserstack"

# ─── Write config.yaml ───────────────────────────────────────

cat > "$CONFIG_FILE" <<EOF
# Generated by setup-config.sh on $(date +%Y-%m-%d)

dev_dir: $DEV_DIR
kafka_home: $KAFKA_HOME
elasticsearch_bin: $ES_BIN

nvm_dir: $NVM_DIR
node_versions:
  v16: $NODE16
  v18: $NODE18
  v20: $NODE20
  v22: $NODE22

rvm_dir: $RVM_DIR
ruby_version: $RUBY_VERSION
ruby_gemset: $RUBY_GEMSET

postgres:
  user: $PG_USER
  password: $PG_PASS
  database: $PG_DB

mysql:
  user: $MY_USER
  password: $MY_PASS
  testhub_database: $MY_TESTHUB_DB

elasticsearch:
  user: $ES_USER
  password: $ES_PASS

git_org: $GIT_ORG
EOF

echo ""
ok "config.yaml written to $CONFIG_FILE"
echo ""
echo "  Next: run 'cd $DEV_DIR && tilt up'"
echo ""
